name: firstJob
'on':
  push: null
jobs:
  job1:
    name: First Job change
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: env | sort
