name: firstJob

on: [push]

jobs:
  job1:
     name: First Job change
     runs-on: ubuntu-latest
     steps:
     -name: Step one
      uses: actions/checkout@v2
     -name: step two
      run: env | sort